### ISSUE TITLE
Bad visibility in Firefox with dark theme

### ISSUE THREAD

**Issue by supermamie** [DesignandHuman/qui-possede-les-medias#38]
I use Firefox on Ubuntu, with Cinnamon and a dark theme ( https://cinnamon-spices.linuxmint.com/themes/view/Adapta-Nokto )
Firefox also has a dark theme ( https://addons.mozilla.org/fr/firefox/addon/arc-dark-theme-we/ )
(I link to both as I am not 100% sure it is only Firefox Theme that causes the problem, with the default theme I have the same problem)

In the page of a media, it is easy to read the informations, but when I click on the plugin, the text is dark on a dark-grey background, so hard to read

![dark-theme](https://user-images.githubusercontent.com/693751/73053787-fa0f4300-3e88-11ea-923c-66d0736e2e19.png)

**Comment by LeoColomb** [comment]
Thanks a lot for your report @supermamie!
I confirm I have the same behavior on my side.
We'll provide a fix soon.

**Comment by LeoColomb** [comment]
Thanks again.
Should be fixed in the next release (we're still waiting for Chrome Web Store approval before sending new versions to stores).

**Comment by supermamie** [comment]
Is it possible to re-open this issue ?

![image](https://user-images.githubusercontent.com/693751/93770486-87738480-fc1c-11ea-80ad-e9def8e95eaa.png)

I'm on version 20.9.16

Maybe it is a problem on my side, but I don't know how.

On a side note, in the plugin options, there is also this problem
![image](https://user-images.githubusercontent.com/693751/93770672-c73a6c00-fc1c-11ea-8011-d05b05024797.png)
(All my others modules are fine in their settings)

**Comment by LeoColomb** [comment]
@supermamie Oh wow, sure!

**Comment by LeoColomb** [comment]
And closed via https://github.com/DesignandHuman/qui-possede-les-medias/commit/a9ed1d87534fcf74e208e9b2179411f92a3a7913

Will be deployed available tomorrow morning.
Thanks for your report again! 👍
