### ISSUE TITLE
Nom et description

### ISSUE THREAD

**Issue by LeoColomb** [DesignandHuman/qui-possede-les-medias#4]

**Comment by Geoffreydorne** [comment]
**Titre :** Qui possède les médias ?

**Titre long :** Qui possède les grands médias que nous lisons ?

**Description :** Apprenons à faire connaissance avec les actionnaires majoritaires des grands médias que nous lisons quotidiennement.

**Description longue :** Les usages de l'information en ligne évoluent et nous accédons dorénavant à l'information par les réseaux sociaux, par des liens, des sources diverses. Ainsi, il est fréquent de lire une actualité sans faire forcément attention au média sur lequel nous lisons cette actualité. Ce plugin permet donc de savoir à qui appartient (_groupe et actionnaire majoritaire_) les médias sur lesquels nous naviguons. Cela permet d'une part de mieux connaître ces actionnaires majoritaires via un lien sur Wikipedia mais également d'aiguiser son regard sur le contenu de chaque média à la lecture de ces informations complémentaires.
