### ISSUE TITLE
Support du mode sompre

### ISSUE THREAD

**Issue by joachimesque** [DesignandHuman/qui-possede-les-medias#40]
Sur mon Mac j'ai un mode sombre (dark mode). Le fond par défaut du menu est sombre, et le texte est noir, donc je ne peux rien lire (voir capture d'écran). Il faut soit spécifier une couleur de fond pour tous les usages (blanc, ou gris clair), soit détecter le mode sombre (via `prefers-color-scheme` il me semble) et ajuster les couleurs.

<img width="329" alt="capture d'écran" src="https://user-images.githubusercontent.com/1781070/73204414-323fab80-413f-11ea-8f88-01d44051bfed.png">

**Comment by LeoColomb** [comment]
Merci d'avoir ce ticket @joachimesque !
Le problème a déjà été rapporté : #38 
La correction viendra avec la prochaine version (très bientôt) 🙂

**Comment by joachimesque** [comment]
Ah merci, et désolé ! (et je me rends compte que dans mon empressement j'avais écrit "sompre" 😬)
