### ISSUE TITLE
Fixer la génération du texte

### ISSUE THREAD

**Issue by LeoColomb** [DesignandHuman/qui-possede-les-medias#6]

**Comment by LeoColomb** [comment]
> "ce média appartient à Xavier Niel et monsieur machin — Groupe bidule"

ou

> "Ce média, du groupe bidule, appartient à Xavier Niel et Monsieur machin"

Les deux sont bons, mais je trouve le second plus simple et à faire et à lire.

Après on peut se passer de "phrasing" et faire des tags.

> **Groupe**
> Blah
>
> **Propriétaires**
> Truc
> Machin

**Comment by Geoffreydorne** [comment]
Oui,
Gardons la seconde formulation. Le phrasing est important vu qu’on
s’adresse à des humains 😎

**Comment by LeoColomb** [comment]
👍

**Comment by Geoffreydorne** [comment]
Je valide donc 

Ce média, du groupe **bidule**, appartient à **bidule**.
ou
Ce média du groupe **bidule** appartient à **bidule** et **bidule**.

Peux-tu mettre ça en place ? :)

**Comment by LeoColomb** [comment]
OK !
