### ISSUE TITLE
Soumissions stores

### ISSUE THREAD

**Issue by LeoColomb** [DesignandHuman/qui-possede-les-medias#7]
* Obtenir les identifiants des extensions
* Obtenir les clés de publication ([doc](https://github.com/LinusU/wext-shipit#credentials))
* Mise en place de la publication automatique

- [X] Firefox
- [ ] Chrome

**Comment by Geoffreydorne** [comment]
[pour moi]
Lien pour uploader un Plugin Chrome dans son ZIP : https://chrome.google.com/webstore/developer/dashboard
Lien pour uploader un Plugin Firefox dans son ZIP : 
https://addons.mozilla.org/fr/developers/

**Comment by LeoColomb** [comment]
Une fois les stores initiés avec un premier envoi du zip et les plugins validés :
* Aller sur [ce lien](https://addons.mozilla.org/en-GB/developers/addon/api/key/). Deux variables sont générées : 
   * "JWT issuer"
   * "JWT secret"
* Suivre [ce guide](https://developer.chrome.com/webstore/using_webstore_api#beforeyoubegin) jusqu'à obtenir les trois variables (seulement la première partie, très rapide) :
  * Client ID (étape 7 ou 8)
  * Client Secret (étape 7 ou 8)
  * Code/Token (étape 9)

Toutes ces variables sont privées et ne doivent pas être diffusées ! Tu peux me les transmettre en mp ou par mail 👍
